//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea_4
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Consumo_Agua
    {
        [Required(ErrorMessage = "El campo es obligatorio.")]
        public int IdCliente { get; set; }
        public int Id { get; set; }
        public int ConsumoActualAgua { get; set; }
        public int Periodo { get; set; }
        public int PromedioConsumoAgua { get; set; }
    
        public virtual Cliente Cliente { get; set; }
       
    }
}
